name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
  release:
    runs-on: ubuntu-latest
    needs: [ verify ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}